// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm

import (
	"fmt"
	"strings"
	"testing"

	"github.com/hashicorp/terraform/helper/acctest"
	"github.com/hashicorp/terraform/helper/resource"
	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/tf"
)

func TestAccDataSourceAzureRMBatchAccount_basic(t *testing.T) {
	dataSourceName := "data.azurerm_batch_account.test"
	ri := tf.AccRandTimeInt()
	location := testLocation()
	rs := strings.ToLower(acctest.RandString(11))

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:  func() { testAccPreCheck(t) },
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceBatchAccount_basic(ri, location, rs),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(dataSourceName, "pool_allocation_mode", "BatchService"),
					resource.TestCheckResourceAttrSet(dataSourceName, "storage_account_id"),
				),
			},
		},
	})
}

func testAccDataSourceBatchAccount_basic(rInt int, location string, rString string) string {
	config := testAccAzureRMBatchAccount_basic(rInt, location, rString)
	return fmt.Sprintf(`
%s

data "azurerm_batch_account" "test" {
  name                = "${azurerm_batch_account.test.name}"
  resource_group_name = "${azurerm_batch_account.test.resource_group_name}"
}
`, config)
}
