// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform/helper/resource"
	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/tf"
)

func TestAccDataSourceAzureRMApiManagementApiRelease_basic(t *testing.T) {
	dataSourceName := "data.azurerm_api_management_api_release.test"
	ri := tf.AccRandTimeInt()
	location := testLocation()

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:  func() { testAccPreCheck(t) },
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceApiManagementApiRelease_basic(ri, location),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet(dataSourceName, "api_id"),
					resource.TestCheckResourceAttr(dataSourceName, "notes", "test release"),
				),
			},
		},
	})
}

func testAccDataSourceApiManagementApiRelease_basic(rInt int, location string) string {
	config := testAccAzureRMApiManagementApiRelease_basic(rInt, location)
	return fmt.Sprintf(`
%s

data "azurerm_api_management_api_release" "test" {
  resource_group_name = "${azurerm_api_management_api_release.test.resource_group_name}"
  api_management_name = "${azurerm_api_management_api_release.test.api_management_name}"
  api_name            = "${azurerm_api_management_api_release.test.api_name}"
}
`, config)
}
