// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm

import (
	"fmt"
	"log"

	"github.com/hashicorp/terraform/helper/schema"
	"github.com/hashicorp/terraform/helper/validation"
	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure"
	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/response"
	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/tf"
	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/utils"
)

func resourceArmFrontDoor() *schema.Resource {
	return &schema.Resource{
		Create: resourceArmFrontDoorCreateUpdate,
		Read:   resourceArmFrontDoorRead,
		Update: resourceArmFrontDoorCreateUpdate,
		Delete: resourceArmFrontDoorDelete,

		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},

		Schema: map[string]*schema.Schema{
			"name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"location": azure.SchemaLocation(),

			"resource_group": azure.SchemaResourceGroupNameDiffSuppress(),

			"backend_pools": {
				Type:     schema.TypeList,
				Optional: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"backends": {
							Type:     schema.TypeList,
							Optional: true,
							MaxItems: 1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"address": {
										Type:     schema.TypeString,
										Optional: true,
									},
									"backend_host_header": {
										Type:     schema.TypeString,
										Optional: true,
									},
									"enabled_state": {
										Type:     schema.TypeString,
										Optional: true,
										ValidateFunc: validation.StringInSlice([]string{
											string(frontdoor.Enabled),
											string(frontdoor.Disabled),
										}, false),
										Default: string(frontdoor.Enabled),
									},
									"http_port": {
										Type:     schema.TypeInt,
										Optional: true,
									},
									"https_port": {
										Type:     schema.TypeInt,
										Optional: true,
									},
									"priority": {
										Type:     schema.TypeInt,
										Optional: true,
									},
									"weight": {
										Type:     schema.TypeInt,
										Optional: true,
									},
								},
							},
						},
						"health_probe_settings": {
							Type:     schema.TypeList,
							Optional: true,
							MaxItems: 1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"id": {
										Type:     schema.TypeString,
										Optional: true,
									},
								},
							},
						},
						"id": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"load_balancing_settings": {
							Type:     schema.TypeList,
							Optional: true,
							MaxItems: 1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"id": {
										Type:     schema.TypeString,
										Optional: true,
									},
								},
							},
						},
						"name": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"resource_state": {
							Type:     schema.TypeString,
							Optional: true,
							ValidateFunc: validation.StringInSlice([]string{
								string(frontdoor.PolicyResourceStateCreating),
								string(frontdoor.PolicyResourceStateEnabling),
								string(frontdoor.PolicyResourceStateEnabled),
								string(frontdoor.PolicyResourceStateDisabling),
								string(frontdoor.PolicyResourceStateDisabled),
								string(frontdoor.PolicyResourceStateDeleting),
							}, false),
							Default: string(frontdoor.PolicyResourceStateCreating),
						},
					},
				},
			},

			"backend_pools_settings": {
				Type:     schema.TypeList,
				Optional: true,
				MaxItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"enforce_certificate_name_check": {
							Type:     schema.TypeString,
							Optional: true,
							ValidateFunc: validation.StringInSlice([]string{
								string(frontdoor.Enabled),
								string(frontdoor.Disabled),
							}, false),
							Default: string(frontdoor.Enabled),
						},
					},
				},
			},

			"enabled_state": {
				Type:     schema.TypeString,
				Optional: true,
				ValidateFunc: validation.StringInSlice([]string{
					string(frontdoor.Enabled),
					string(frontdoor.Disabled),
				}, false),
				Default: string(frontdoor.Enabled),
			},

			"friendly_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"frontend_endpoints": {
				Type:     schema.TypeList,
				Optional: true,
				MaxItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"host_name": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"id": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"name": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"resource_state": {
							Type:     schema.TypeString,
							Optional: true,
							ValidateFunc: validation.StringInSlice([]string{
								string(frontdoor.PolicyResourceStateCreating),
								string(frontdoor.PolicyResourceStateEnabling),
								string(frontdoor.PolicyResourceStateEnabled),
								string(frontdoor.PolicyResourceStateDisabling),
								string(frontdoor.PolicyResourceStateDisabled),
								string(frontdoor.PolicyResourceStateDeleting),
							}, false),
							Default: string(frontdoor.PolicyResourceStateCreating),
						},
						"session_affinity_enabled_state": {
							Type:     schema.TypeString,
							Optional: true,
							ValidateFunc: validation.StringInSlice([]string{
								string(frontdoor.Enabled),
								string(frontdoor.Disabled),
							}, false),
							Default: string(frontdoor.Enabled),
						},
						"session_affinity_ttl_seconds": {
							Type:     schema.TypeInt,
							Optional: true,
						},
						"web_application_firewall_policy_link": {
							Type:     schema.TypeList,
							Optional: true,
							MaxItems: 1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"id": {
										Type:     schema.TypeString,
										Optional: true,
									},
								},
							},
						},
					},
				},
			},

			"health_probe_settings": {
				Type:     schema.TypeList,
				Optional: true,
				MaxItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"interval_in_seconds": {
							Type:     schema.TypeInt,
							Optional: true,
						},
						"name": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"path": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"protocol": {
							Type:     schema.TypeString,
							Optional: true,
							ValidateFunc: validation.StringInSlice([]string{
								string(frontdoor.Http),
								string(frontdoor.Https),
							}, false),
							Default: string(frontdoor.Http),
						},
						"resource_state": {
							Type:     schema.TypeString,
							Optional: true,
							ValidateFunc: validation.StringInSlice([]string{
								string(frontdoor.PolicyResourceStateCreating),
								string(frontdoor.PolicyResourceStateEnabling),
								string(frontdoor.PolicyResourceStateEnabled),
								string(frontdoor.PolicyResourceStateDisabling),
								string(frontdoor.PolicyResourceStateDisabled),
								string(frontdoor.PolicyResourceStateDeleting),
							}, false),
							Default: string(frontdoor.PolicyResourceStateCreating),
						},
					},
				},
			},

			"load_balancing_settings": {
				Type:     schema.TypeList,
				Optional: true,
				MaxItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"additional_latency_milliseconds": {
							Type:     schema.TypeInt,
							Optional: true,
						},
						"id": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"name": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"resource_state": {
							Type:     schema.TypeString,
							Optional: true,
							ValidateFunc: validation.StringInSlice([]string{
								string(frontdoor.Creating),
								string(frontdoor.Enabling),
								string(frontdoor.Enabled),
								string(frontdoor.Disabling),
								string(frontdoor.Disabled),
								string(frontdoor.Deleting),
							}, false),
							Default: string(frontdoor.Creating),
						},
						"sample_size": {
							Type:     schema.TypeInt,
							Optional: true,
						},
						"successful_samples_required": {
							Type:     schema.TypeInt,
							Optional: true,
						},
					},
				},
			},

			"resource_state": {
				Type:     schema.TypeString,
				Optional: true,
				ValidateFunc: validation.StringInSlice([]string{
					string(frontdoor.PolicyResourceStateCreating),
					string(frontdoor.PolicyResourceStateEnabling),
					string(frontdoor.PolicyResourceStateEnabled),
					string(frontdoor.PolicyResourceStateDisabling),
					string(frontdoor.PolicyResourceStateDisabled),
					string(frontdoor.PolicyResourceStateDeleting),
				}, false),
				Default: string(frontdoor.PolicyResourceStateCreating),
			},

			"routing_rules": {
				Type:     schema.TypeList,
				Optional: true,
				MaxItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"accepted_protocols": {
							Type:     schema.TypeString,
							Optional: true,
							ValidateFunc: validation.StringInSlice([]string{
								string(frontdoor.Http),
								string(frontdoor.Https),
							}, false),
							Default: string(frontdoor.Http),
						},
						"enabled_state": {
							Type:     schema.TypeString,
							Optional: true,
							ValidateFunc: validation.StringInSlice([]string{
								string(frontdoor.Enabled),
								string(frontdoor.Disabled),
							}, false),
							Default: string(frontdoor.Enabled),
						},
						"frontend_endpoints": {
							Type:     schema.TypeList,
							Optional: true,
							MaxItems: 1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"id": {
										Type:     schema.TypeString,
										Optional: true,
									},
								},
							},
						},
						"id": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"name": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"patterns_to_match": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"resource_state": {
							Type:     schema.TypeString,
							Optional: true,
							ValidateFunc: validation.StringInSlice([]string{
								string(frontdoor.Creating),
								string(frontdoor.Enabling),
								string(frontdoor.Enabled),
								string(frontdoor.Disabling),
								string(frontdoor.Disabled),
								string(frontdoor.Deleting),
							}, false),
							Default: string(frontdoor.Creating),
						},
					},
				},
			},

			"tags": tagsSchema(),

			"cname": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"provisioning_state": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"type": {
				Type:     schema.TypeString,
				Computed: true,
			},
		},
	}
}

func resourceArmFrontDoorCreateUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*ArmClient).frontDoorsClient
	ctx := meta.(*ArmClient).StopContext

	name := d.Get("name").(string)
	resourceGroup := d.Get("resource_group").(string)

	if requireResourcesToBeImported {
		resp, err := client.Get(ctx, resourceGroup, name)
		if err != nil {
			if !utils.ResponseWasNotFound(resp.Response) {
				return fmt.Errorf("Error checking for present of existing Front Door %q (Resource Group %q): %+v", name, resourceGroup, err)
			}
		}
		if !utils.ResponseWasNotFound(resp.Response) {
			return tf.ImportAsExistsError("azurerm_front_door", *resp.ID)
		}
	}

	location := azure.NormalizeLocation(d.Get("location").(string))
	backendPools := d.Get("backend_pools").([]interface{})
	backendPoolsSettings := d.Get("backend_pools_settings").([]interface{})
	enabledState := d.Get("enabled_state").(string)
	friendlyName := d.Get("friendly_name").(string)
	frontendEndpoints := d.Get("frontend_endpoints").([]interface{})
	healthProbeSettings := d.Get("health_probe_settings").([]interface{})
	loadBalancingSettings := d.Get("load_balancing_settings").([]interface{})
	resourceState := d.Get("resource_state").(string)
	routingRules := d.Get("routing_rules").([]interface{})
	tags := d.Get("tags").(map[string]interface{})

	frontDoorParameters := frontdoor.FrontDoor{
		Location: utils.String(location),
		Properties: &frontdoor.Properties{
			BackendPools:          expandArmFrontDoorBackendPool(backendPools),
			BackendPoolsSettings:  expandArmFrontDoorBackendPoolsSettings(backendPoolsSettings),
			EnabledState:          frontdoor.EnabledState(enabledState),
			FriendlyName:          utils.String(friendlyName),
			FrontendEndpoints:     expandArmFrontDoorFrontendEndpoint(frontendEndpoints),
			HealthProbeSettings:   expandArmFrontDoorHealthProbeSettingsModel(healthProbeSettings),
			LoadBalancingSettings: expandArmFrontDoorLoadBalancingSettingsModel(loadBalancingSettings),
			ResourceState:         frontdoor.ResourceState(resourceState),
			RoutingRules:          expandArmFrontDoorRoutingRule(routingRules),
		},
		Tags: expandTags(tags),
	}

	future, err := client.CreateOrUpdate(ctx, resourceGroup, name, frontDoorParameters)
	if err != nil {
		return fmt.Errorf("Error creating Front Door %q (Resource Group %q): %+v", name, resourceGroup, err)
	}
	if err = future.WaitForCompletionRef(ctx, client.Client); err != nil {
		return fmt.Errorf("Error waiting for creation of Front Door %q (Resource Group %q): %+v", name, resourceGroup, err)
	}

	resp, err := client.Get(ctx, resourceGroup, name)
	if err != nil {
		return fmt.Errorf("Error retrieving Front Door %q (Resource Group %q): %+v", name, resourceGroup, err)
	}
	if resp.ID == nil {
		return fmt.Errorf("Cannot read Front Door %q (Resource Group %q) ID", name, resourceGroup)
	}
	d.SetId(*resp.ID)

	return resourceArmFrontDoorRead(d, meta)
}

func resourceArmFrontDoorRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*ArmClient).frontDoorsClient
	ctx := meta.(*ArmClient).StopContext

	id, err := parseAzureResourceID(d.Id())
	if err != nil {
		return err
	}
	resourceGroup := id.ResourceGroup
	name := id.Path["frontDoors"]

	resp, err := client.Get(ctx, resourceGroup, name)
	if err != nil {
		if utils.ResponseWasNotFound(resp.Response) {
			log.Printf("[INFO] Front Door %q does not exist - removing from state", d.Id())
			d.SetId("")
			return nil
		}
		return fmt.Errorf("Error reading Front Door %q (Resource Group %q): %+v", name, resourceGroup, err)
	}

	d.Set("name", resp.Name)
	d.Set("resource_group", resourceGroup)
	if location := resp.Location; location != nil {
		d.Set("location", azure.NormalizeLocation(*location))
	}
	if properties := resp.Properties; properties != nil {
		if err := d.Set("backend_pools", flattenArmFrontDoorBackendPool(properties.BackendPools)); err != nil {
			return fmt.Errorf("Error setting `backend_pools`: %+v", err)
		}
		if err := d.Set("backend_pools_settings", flattenArmFrontDoorBackendPoolsSettings(properties.BackendPoolsSettings)); err != nil {
			return fmt.Errorf("Error setting `backend_pools_settings`: %+v", err)
		}
		d.Set("cname", properties.Cname)
		d.Set("enabled_state", string(properties.EnabledState))
		d.Set("friendly_name", properties.FriendlyName)
		if err := d.Set("frontend_endpoints", flattenArmFrontDoorFrontendEndpoint(properties.FrontendEndpoints)); err != nil {
			return fmt.Errorf("Error setting `frontend_endpoints`: %+v", err)
		}
		if err := d.Set("health_probe_settings", flattenArmFrontDoorHealthProbeSettingsModel(properties.HealthProbeSettings)); err != nil {
			return fmt.Errorf("Error setting `health_probe_settings`: %+v", err)
		}
		if err := d.Set("load_balancing_settings", flattenArmFrontDoorLoadBalancingSettingsModel(properties.LoadBalancingSettings)); err != nil {
			return fmt.Errorf("Error setting `load_balancing_settings`: %+v", err)
		}
		d.Set("provisioning_state", properties.ProvisioningState)
		d.Set("resource_state", string(properties.ResourceState))
		if err := d.Set("routing_rules", flattenArmFrontDoorRoutingRule(properties.RoutingRules)); err != nil {
			return fmt.Errorf("Error setting `routing_rules`: %+v", err)
		}
	}
	d.Set("type", resp.Type)
	flattenAndSetTags(d, resp.Tags)

	return nil
}

func resourceArmFrontDoorDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*ArmClient).frontDoorsClient
	ctx := meta.(*ArmClient).StopContext

	id, err := parseAzureResourceID(d.Id())
	if err != nil {
		return err
	}
	resourceGroup := id.ResourceGroup
	name := id.Path["frontDoors"]

	future, err := client.Delete(ctx, resourceGroup, name)
	if err != nil {
		if response.WasNotFound(future.Response()) {
			return nil
		}
		return fmt.Errorf("Error deleting Front Door %q (Resource Group %q): %+v", name, resourceGroup, err)
	}

	if err = future.WaitForCompletionRef(ctx, client.Client); err != nil {
		if !response.WasNotFound(future.Response()) {
			return fmt.Errorf("Error waiting for deleting Front Door %q (Resource Group %q): %+v", name, resourceGroup, err)
		}
	}

	return nil
}

func expandArmFrontDoorBackendPool(input []interface{}) *[]frontdoor.BackendPool {
	results := make([]frontdoor.BackendPool, 0)
	for _, v := range input {
		id := v["id"].(string)
		backends := v["backends"].([]interface{})
		loadBalancingSettings := v["load_balancing_settings"].([]interface{})
		healthProbeSettings := v["health_probe_settings"].([]interface{})
		resourceState := v["resource_state"].(string)
		name := v["name"].(string)

		item := frontdoor.BackendPool{
			ID:   utils.String(id),
			Name: utils.String(name),
			Properties: &frontdoor.BackendPoolProperties{
				Backends:              expandArmFrontDoorBackend(backends),
				HealthProbeSettings:   expandArmFrontDoorSubResource(healthProbeSettings),
				LoadBalancingSettings: expandArmFrontDoorSubResource(loadBalancingSettings),
				ResourceState:         frontdoor.ResourceState(resourceState),
			},
		}

		results = append(results, item)
	}
	return &results
}

func expandArmFrontDoorBackendPoolsSettings(input []interface{}) *frontdoor.BackendPoolsSettings {
	if len(input) == 0 {
		return nil
	}
	v := input[0].(map[string]interface{})

	enforceCertificateNameCheck := v["enforce_certificate_name_check"].(string)

	result := frontdoor.BackendPoolsSettings{
		EnforceCertificateNameCheck: frontdoor.EnforceCertificateNameCheckEnabledState(enforceCertificateNameCheck),
	}
	return &result
}

func expandArmFrontDoorFrontendEndpoint(input []interface{}) *frontdoor.FrontendEndpoint {
	if len(input) == 0 {
		return nil
	}
	v := input[0].(map[string]interface{})

	id := v["id"].(string)
	hostName := v["host_name"].(string)
	sessionAffinityEnabledState := v["session_affinity_enabled_state"].(string)
	sessionAffinityTtlSeconds := v["session_affinity_ttl_seconds"].(int)
	webApplicationFirewallPolicyLink := v["web_application_firewall_policy_link"].([]interface{})
	resourceState := v["resource_state"].(string)
	name := v["name"].(string)

	result := frontdoor.FrontendEndpoint{
		ID:   utils.String(id),
		Name: utils.String(name),
		Properties: &frontdoor.FrontendEndpointProperties{
			HostName:                         utils.String(hostName),
			ResourceState:                    frontdoor.ResourceState(resourceState),
			SessionAffinityEnabledState:      frontdoor.SessionAffinityEnabledState(sessionAffinityEnabledState),
			SessionAffinityTtlSeconds:        utils.Int(sessionAffinityTtlSeconds),
			WebApplicationFirewallPolicyLink: expandArmFrontDoorFrontendEndpointUpdateParameters_webApplicationFirewallPolicyLink(webApplicationFirewallPolicyLink),
		},
	}
	return &result
}

func expandArmFrontDoorHealthProbeSettingsModel(input []interface{}) *frontdoor.HealthProbeSettingsModel {
	if len(input) == 0 {
		return nil
	}
	v := input[0].(map[string]interface{})

	id := v["id"].(string)
	path := v["path"].(string)
	protocol := v["protocol"].(string)
	intervalInSeconds := v["interval_in_seconds"].(int)
	resourceState := v["resource_state"].(string)
	name := v["name"].(string)

	result := frontdoor.HealthProbeSettingsModel{
		ID:   utils.String(id),
		Name: utils.String(name),
		Properties: &frontdoor.HealthProbeSettingsProperties{
			IntervalInSeconds: utils.Int(intervalInSeconds),
			Path:              utils.String(path),
			Protocol:          frontdoor.Protocol(protocol),
			ResourceState:     frontdoor.ResourceState(resourceState),
		},
	}
	return &result
}

func expandArmFrontDoorLoadBalancingSettingsModel(input []interface{}) *frontdoor.LoadBalancingSettingsModel {
	if len(input) == 0 {
		return nil
	}
	v := input[0].(map[string]interface{})

	id := v["id"].(string)
	sampleSize := v["sample_size"].(int)
	successfulSamplesRequired := v["successful_samples_required"].(int)
	additionalLatencyMilliseconds := v["additional_latency_milliseconds"].(int)
	resourceState := v["resource_state"].(string)
	name := v["name"].(string)

	result := frontdoor.LoadBalancingSettingsModel{
		ID:   utils.String(id),
		Name: utils.String(name),
		Properties: &frontdoor.LoadBalancingSettingsProperties{
			AdditionalLatencyMilliseconds: utils.Int(additionalLatencyMilliseconds),
			ResourceState:                 frontdoor.ResourceState(resourceState),
			SampleSize:                    utils.Int(sampleSize),
			SuccessfulSamplesRequired:     utils.Int(successfulSamplesRequired),
		},
	}
	return &result
}

func expandArmFrontDoorRoutingRule(input []interface{}) *frontdoor.RoutingRule {
	if len(input) == 0 {
		return nil
	}
	v := input[0].(map[string]interface{})

	id := v["id"].(string)
	frontendEndpoints := v["frontend_endpoints"].([]interface{})
	acceptedProtocols := v["accepted_protocols"].(string)
	patternsToMatch := v["patterns_to_match"].(string)
	enabledState := v["enabled_state"].(string)
	resourceState := v["resource_state"].(string)
	name := v["name"].(string)

	result := frontdoor.RoutingRule{
		ID:   utils.String(id),
		Name: utils.String(name),
		Properties: &frontdoor.RoutingRuleProperties{
			AcceptedProtocols: frontdoor.Protocol(acceptedProtocols),
			EnabledState:      frontdoor.routingRuleEnabledState(enabledState),
			FrontendEndpoints: expandArmFrontDoorSubResource(frontendEndpoints),
			PatternsToMatch:   utils.String(patternsToMatch),
			ResourceState:     frontdoor.ResourceState(resourceState),
		},
	}
	return &result
}

func expandArmFrontDoorBackend(input []interface{}) *frontdoor.Backend {
	if len(input) == 0 {
		return nil
	}
	v := input[0].(map[string]interface{})

	address := v["address"].(string)
	httpPort := v["http_port"].(int)
	httpsPort := v["https_port"].(int)
	enabledState := v["enabled_state"].(string)
	priority := v["priority"].(int)
	weight := v["weight"].(int)
	backendHostHeader := v["backend_host_header"].(string)

	result := frontdoor.Backend{
		Address:           utils.String(address),
		BackendHostHeader: utils.String(backendHostHeader),
		EnabledState:      frontdoor.backendEnabledState(enabledState),
		HttpPort:          utils.Int(httpPort),
		HttpsPort:         utils.Int(httpsPort),
		Priority:          utils.Int(priority),
		Weight:            utils.Int(weight),
	}
	return &result
}

func expandArmFrontDoorSubResource(input []interface{}) *frontdoor.SubResource {
	if len(input) == 0 {
		return nil
	}
	v := input[0].(map[string]interface{})

	id := v["id"].(string)

	result := frontdoor.SubResource{
		ID: utils.String(id),
	}
	return &result
}

func expandArmFrontDoorFrontendEndpointUpdateParameters_webApplicationFirewallPolicyLink(input []interface{}) *frontdoor.FrontendEndpointUpdateParameters_webApplicationFirewallPolicyLink {
	if len(input) == 0 {
		return nil
	}
	v := input[0].(map[string]interface{})

	id := v["id"].(string)

	result := frontdoor.FrontendEndpointUpdateParameters_webApplicationFirewallPolicyLink{
		ID: utils.String(id),
	}
	return &result
}

func flattenArmFrontDoorBackendPool(input *[]frontdoor.BackendPool) []interface{} {
	results := make([]interface{}, 0)
	if input == nil {
		return results
	}

	for _, item := range input {
		v := make(map[string]interface{})

		if id := item.ID; id != nil {
			v["id"] = *id
		}
		if properties := item.Properties; properties != nil {
			v["backends"] = flattenArmFrontDoorBackend(properties.Backends)
			v["health_probe_settings"] = flattenArmFrontDoorSubResource(properties.HealthProbeSettings)
			v["load_balancing_settings"] = flattenArmFrontDoorSubResource(properties.LoadBalancingSettings)
			v["resource_state"] = string(properties.ResourceState)
		}

		results = append(results, v)
	}

	return results
}

func flattenArmFrontDoorBackendPoolsSettings(input *frontdoor.BackendPoolsSettings) []interface{} {
	if input == nil {
		return make([]interface{}, 0)
	}

	result := make(map[string]interface{})

	result["enforce_certificate_name_check"] = string(input.EnforceCertificateNameCheck)

	return []interface{}{result}
}

func flattenArmFrontDoorFrontendEndpoint(input *frontdoor.FrontendEndpoint) []interface{} {
	if input == nil {
		return make([]interface{}, 0)
	}

	result := make(map[string]interface{})

	if id := input.ID; id != nil {
		result["id"] = *id
	}
	if properties := input.Properties; properties != nil {
		if hostName := properties.HostName; hostName != nil {
			result["host_name"] = *hostName
		}
		result["resource_state"] = string(properties.ResourceState)
		result["session_affinity_enabled_state"] = string(properties.SessionAffinityEnabledState)
		if sessionAffinityTtlSeconds := properties.SessionAffinityTtlSeconds; sessionAffinityTtlSeconds != nil {
			result["session_affinity_ttl_seconds"] = *sessionAffinityTtlSeconds
		}
		result["web_application_firewall_policy_link"] = flattenArmFrontDoorFrontendEndpointUpdateParametersWebApplicationFirewallPolicyLink(properties.WebApplicationFirewallPolicyLink)
	}

	return []interface{}{result}
}

func flattenArmFrontDoorHealthProbeSettingsModel(input *frontdoor.HealthProbeSettingsModel) []interface{} {
	if input == nil {
		return make([]interface{}, 0)
	}

	result := make(map[string]interface{})

	if id := input.ID; id != nil {
		result["id"] = *id
	}
	if properties := input.Properties; properties != nil {
		if intervalInSeconds := properties.IntervalInSeconds; intervalInSeconds != nil {
			result["interval_in_seconds"] = *intervalInSeconds
		}
		if path := properties.Path; path != nil {
			result["path"] = *path
		}
		result["protocol"] = string(properties.Protocol)
		result["resource_state"] = string(properties.ResourceState)
	}

	return []interface{}{result}
}

func flattenArmFrontDoorLoadBalancingSettingsModel(input *frontdoor.LoadBalancingSettingsModel) []interface{} {
	if input == nil {
		return make([]interface{}, 0)
	}

	result := make(map[string]interface{})

	if id := input.ID; id != nil {
		result["id"] = *id
	}
	if properties := input.Properties; properties != nil {
		if additionalLatencyMilliseconds := properties.AdditionalLatencyMilliseconds; additionalLatencyMilliseconds != nil {
			result["additional_latency_milliseconds"] = *additionalLatencyMilliseconds
		}
		result["resource_state"] = string(properties.ResourceState)
		if sampleSize := properties.SampleSize; sampleSize != nil {
			result["sample_size"] = *sampleSize
		}
		if successfulSamplesRequired := properties.SuccessfulSamplesRequired; successfulSamplesRequired != nil {
			result["successful_samples_required"] = *successfulSamplesRequired
		}
	}

	return []interface{}{result}
}

func flattenArmFrontDoorRoutingRule(input *frontdoor.RoutingRule) []interface{} {
	if input == nil {
		return make([]interface{}, 0)
	}

	result := make(map[string]interface{})

	if id := input.ID; id != nil {
		result["id"] = *id
	}
	if properties := input.Properties; properties != nil {
		result["accepted_protocols"] = string(properties.AcceptedProtocols)
		result["enabled_state"] = string(properties.EnabledState)
		result["frontend_endpoints"] = flattenArmFrontDoorSubResource(properties.FrontendEndpoints)
		if patternsToMatch := properties.PatternsToMatch; patternsToMatch != nil {
			result["patterns_to_match"] = *patternsToMatch
		}
		result["resource_state"] = string(properties.ResourceState)
	}

	return []interface{}{result}
}

func flattenArmFrontDoorBackend(input *frontdoor.Backend) []interface{} {
	if input == nil {
		return make([]interface{}, 0)
	}

	result := make(map[string]interface{})

	if address := input.Address; address != nil {
		result["address"] = *address
	}
	if backendHostHeader := input.BackendHostHeader; backendHostHeader != nil {
		result["backend_host_header"] = *backendHostHeader
	}
	result["enabled_state"] = string(input.EnabledState)
	if httpPort := input.HttpPort; httpPort != nil {
		result["http_port"] = *httpPort
	}
	if httpsPort := input.HttpsPort; httpsPort != nil {
		result["https_port"] = *httpsPort
	}
	if priority := input.Priority; priority != nil {
		result["priority"] = *priority
	}
	if weight := input.Weight; weight != nil {
		result["weight"] = *weight
	}

	return []interface{}{result}
}

func flattenArmFrontDoorSubResource(input *frontdoor.SubResource) []interface{} {
	if input == nil {
		return make([]interface{}, 0)
	}

	result := make(map[string]interface{})

	if id := input.ID; id != nil {
		result["id"] = *id
	}

	return []interface{}{result}
}

func flattenArmFrontDoorFrontendEndpointUpdateParametersWebApplicationFirewallPolicyLink(input *frontdoor.FrontendEndpointUpdateParametersWebApplicationFirewallPolicyLink) []interface{} {
	if input == nil {
		return make([]interface{}, 0)
	}

	result := make(map[string]interface{})

	if id := input.ID; id != nil {
		result["id"] = *id
	}

	return []interface{}{result}
}
